### PR TITLE
Support string fields in input_changed?/3

### LINKED ISSUE #427: Should Form.input_changed?/3 accept also string fields?
https://github.com/phoenixframework/phoenix_html/blob/0d394e90e9e3fd9e63cdbec91f0c572c0ebd64b3/lib/phoenix_html/form.ex#L196-L202

Is there a reason why atoms are only accepted here? `FormData.input_value` [accepts](https://hexdocs.pm/phoenix_html/Phoenix.HTML.FormData.html#input_value/3) `Field.t()`, which is `atom() | String.t()`, right?

### PR DESCRIPTION
**Pull request by dvic**
Closes #427

### CODE REVIEW

**Comment by dvic** [comment]
@josevalim should I also change the typespec of `errors` in `Form`? Currently it's `errors: Keyword.t()` but technically that should be `[{atom() | String.t(), term()}]`?

**Comment by josevalim** [comment]
Yes, please.

**Comment by dvic** [comment]
> Yes, please.

Done!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
