### PR TITLE
Allow DateTime to be used with datetime_local_input/3

### PR DESCRIPTION
**Pull request by davydog187**
Paired with @supersimple on this one. 

Found this via testing with the Surface [DateTimeLocalInput](https://surface-ui.org/builtincomponents/DateTimeLocalInput) component. 

As for the expected behavior, this will not take any timezone into account. This seems reasonable to me, but happy to change based on feedback.

### CODE REVIEW

**Comment by josevalim** [comment]
I believe the current behavior is intentional. Ignoring the timeZone should be a explicit decision, I recommend converting to naive explicitly before. :)

**Comment by davydog187** [comment]
@josevalim the problem is that if you give it a datetime, it silently breaks. Do you recommend raising an error then?

**Comment by davydog187** [comment]
Net effect of passing a `DateTime` right now is that it will call `to_string`, which will end up as an improper `value` of the `input` field.

**Comment by davydog187** [comment]
@josevalim did you mean to merge?

**Comment by josevalim** [comment]
Yes, I forgot to write it down though. I figured out that, if the input is a DateTime, it must have been converted to the user local timezone, which may or may not be stored separately, so I think it should be fine to show the DateTime as is rather than asking the users to convert to native.

**Comment by davydog187** [comment]
I thought the same, thank you!

**Pull request merged**
