### PR TITLE
Add reset input in order to reset forms field to their original state

### PR DESCRIPTION
**Pull request by orendon**
```erb
<%= reset "Clear", class: "btn" %>
#=> <input type="reset" value="Clear" class="btn">
```

### CODE REVIEW

**Comment by josevalim** [comment]
:+1: @chrismccord ?

**Comment by chrismccord** [comment]
reset or rest_input ?

**Comment by josevalim** [comment]
We call submit only submit. So reset is in sync.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by chrismccord** [comment]
:+1: thanks!

**Pull request merged**
