### PR TITLE
Fix incorrect examples in docs.

### PR DESCRIPTION
**Pull request by nyaray**
This addresses issue #367

### CODE REVIEW

**Comment by josevalim** [comment]
Your application is not guaranteed to have `page_path` either. I mean, a new application does have a `page_path` but only the `:index` action. The main point is that you should those by your own routes... perhaps we should leave the example as is but add a paragraph saying you should replace `user_path` by the relevant resource/route?

**Comment by nyaray** [comment]
OK, at first I was _very_ confused, because I didn't realise that `user_` in the function name came from the entity one was dealing with. The prefix in the example comes from the fact that it's related to the `UserController`, right?

What I don't understand is how I arrive at the conclusion that the first part of the controller's name is the prefix of the function I want to call in my template. I think that is what needs to be clarified in the extra paragraph you're talking about, which is a good idea, since my edits were made under an incorrect assumption about how Router helper functions were generated.

**Comment by josevalim** [comment]
@nyaray exactly. For forms there is usually something like

    resources :users, UserController

Which means there is a `user_path/2` helper with several actions, `:create` being one of them.

**Comment by nyaray** [comment]
Is that `resources :users ...` generated by a `use` declaration somewhere? I don't have it anywhere, according to my search-entire-project function. If so, that should probably also be part of the explanation.

**Comment by josevalim** [comment]
If you use `mix phx.gen.html`, then it asks you to add it to the router. But in a nutshell, it can be any route previously defined in your router.

**Comment by josevalim** [comment]
Closing for now. If you can think of other improvements, we will be glad to reopen. Thanks!

**Pull request closed without merging**
