### PR TITLE
Use more iodata for tag/2 and content_tag/3

### PR DESCRIPTION
**Pull request by michalmuskala**

### CODE REVIEW

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by drapergeek** [comment]
Forgive my ignorance, I'm unsure of what this is doing or what benefit it provides. Can someone explain this?

**Comment by michalmuskala** [comment]
It avoids copying binaries when building strings.

https://www.bignerdranch.com/blog/elixir-and-io-lists-part-1-building-output-efficiently/ and https://www.bignerdranch.com/blog/elixir-and-io-lists-part-2-io-lists-in-phoenix/ are great articles that go in depth on this.

**Comment by drapergeek** [comment]
Thanks!

**Pull request merged**
