### PR TITLE
Add label/4 tag

### PR DESCRIPTION
**Pull request by gjaldon**
Closes https://github.com/phoenixframework/phoenix_html/issues/9

### CODE REVIEW

**Comment by chrismccord** [comment]
Looks perfect to me. I'll let @josevalim sign off. Thanks!

**Comment by josevalim** [comment]
@chrismccord can you please ship v1.2.0?

**Comment by josevalim** [comment]
(don't forget the changelog)

**Comment by chrismccord** [comment]
Done!

**Pull request merged**
