### PR TITLE
Adding mail_to helper

### PR DESCRIPTION
**Pull request by iloveitaly**
Hello! Thanks for all of the great work here.

Before putting more work into this, I wanted to check and see if this is the sort of addition that would be welcome to the `phoenix_html` package. It seems like this package is relatively lightweight compared to the helpers available in rails, and wanted to see if that was intentional or if contributions to add additional helpers are welcome.

Thanks!

### CODE REVIEW

**Comment by josevalim** [comment]
Thanks, it actually looks good to me!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Hi @iloveitaly! Sorry, this has gone stale but, given it is a very short wrapper around `link`, I think we will be fine without it. Thank you!

**Comment by iloveitaly** [comment]
@josevalim the rails `mail_to` is a lot more robust (URL encodes the email, allows for additional params to customize the message). Are you thinking that a `mail_to` wrapper with that advanced functionality makes sense, but not the simple implementation that is contained in this PR? Or are you trying to keep the surface area of the html helpers small intentionally?

**Comment by josevalim** [comment]
I think it is ok to add mail_to if we provide more functionality around it.

**Pull request closed without merging**
