### PR TITLE
Do not add a class to buttons by default

### PR DESCRIPTION
**Pull request by drapergeek**
It seems like an odd decision to add a class to any markup generated without the user opting into that decision. Happy to hear opinions on this decision but I thought I would get the ball rolling.

### CODE REVIEW

**Comment by josevalim** [comment]
We need to otherwise it is impossible to style those forms which is something we do in the default .css that ships as part of Phoenix. We are glad to make it customizable but we can't remove them.

**Comment by drapergeek** [comment]
>We need to otherwise it is impossible to style those forms which is something we do in the default .css that ships as part of Phoenix. We are glad to make it customizable but we can't remove them.

It's already customizable, which I appreciate.

Why should the framework have any opinion on styling by default? That doesn't seem like something that the framework should be in charge of.

**Comment by josevalim** [comment]
This is just one library, it is not like the framework is imposing this choice on you. :) At the time it looked like a reasonable default as otherwise it would be impossible to style them. In any case, we can't simply remove it now without breaking all applications that are relying on it there.

**Comment by chrismccord** [comment]
I agree it's a tradeoff, but you can easily wrap the the link and button functions `import ... except: [link: 2, button: 2]` and use your own behaviour/styling.

**Comment by drapergeek** [comment]
Fair enough, thanks for the awesome library!

**Pull request closed without merging**
