### PR TITLE
Add date, datetime and time input types

### PR DESCRIPTION
**Pull request by vortizhe**
Hi, I miss date and time input types. 

I think input[type=datetime] it's necessary for using native datepickers on modern and mobile browsers .

### CODE REVIEW

**Comment by josevalim** [comment]
I believe `type="datetime"` is no longer supported and removed from most browsers in favor of local_datetime.

**Comment by nekath** [comment]
It looks like datetime is no longer supported.
see: https://github.com/whatwg/html/issues/336

`datetime-local` is the correct type
see: https://www.w3.org/TR/2012/WD-html-markup-20120315/input.datetime-local.html

**Comment by vortizhe** [comment]
True, isn't deprecated yet, at least on chrome but `type=datetime-local` is more future proof.

I update it.

**Comment by josevalim** [comment]
Thank you! I would also like to see tests where the values are the Time, Date and NaiveDateTime structs. And I would probably rename datetime_local_input to naive_datetime_input.

**Comment by josevalim** [comment]
Ping? We should standardize around Elixir's calendar types at this point.

**Comment by florish** [comment]
@vortizhe Thanks for opening this, I was looking for a `date_input` function in the docs, but it turns out, there isn't one yet. Is it still on your list to finish this PR? If not, I could pick it up and proess @josevalim 's feedback on the `naive_datetime_input` rename and additional tests.

**Pull request closed without merging**
